### ISSUE TITLE
Only first two images are read from multipage TIFF.

### ISSUE THREAD

**Issue by tdhintz** [drewnoakes/metadata-extractor-dotnet#102]
HasFollowerIfd() is hard-coded to treat multipage TIFF as a single image + thumbnail if the optional ExifDirectoryBase.TagPageNumber tag isn't present.  Thus, a 5 page file only presents tags from the first two.  The page number tag is rarely present.

**Comment by kwhopper** [comment]
Do you know of an image in the image repo or have an image you can share that exhibits this behavior? I'm not saying it isn't an issue, but need one to test. Thanks

**Comment by tdhintz** [comment]
I created an image that can be used for testing.  What is the best way to share it with you?

**Comment by kwhopper** [comment]
If the file is small enough, you should be able to add it through the comment box. "Attach files..." is just below the entry area.

Zip is usually a good idea. A very large file, or a file you want to keep private after sharing, might require a hosting service.

**Comment by tdhintz** [comment]
I made it a pull request.

**Comment by kwhopper** [comment]
@tdhintz - the proposed fix in merged. You can fork/download the main project again and build the new assembly with Visual Studio 2017 if you want to test it. Thanks

**Comment by drewnoakes** [comment]
Closing as fixed.
