### ISSUE TITLE
timing of next production release?

### ISSUE THREAD

**Issue by twest820** [drewnoakes/metadata-extractor-dotnet#105]
Hi Drew, do you have a sense of when the next production nuget for Metadata Extractor will be available?  RC2 is coming up on five months old now.

**Comment by drewnoakes** [comment]
Hi Todd, you're right. It's long overdue. I haven't had much time lately.

For the next release I was hoping to integrate #91 (drewnoakes/metadata-extractor#232).

This will also be the first release with a strong name package.

**Comment by drewnoakes** [comment]
I'll find some time this weekend.

**Comment by twest820** [comment]
Cool, thanks for the update.  No need to hustle on my account; a production release by the end of this month would fit conveniently with my release schedule but even mid-June would work too.

**Comment by drewnoakes** [comment]
Apologies too to @kwhopper for the delay with his PR.

**Comment by kwhopper** [comment]
No problem. I have other changes for that PR in progress, but they aren't ready to push yet.

**Comment by twest820** [comment]
How's this looking?

**Comment by twest820** [comment]
Bump.

**Comment by drewnoakes** [comment]
@twest820 2.0 is up on NuGet now. Please try it out.

Apologies for the delay. I've had some family stuff going on recently and haven't touched my laptop this month.
