### ISSUE TITLE
IPTC Creator / Rights

### ISSUE THREAD

**Issue by MadsSwensson** [drewnoakes/metadata-extractor-dotnet#108]
Hi

Using Adobe Bridge CC 2015 and [this](http://metadatadeluxe.pbworks.com/w/page/108523528/VRA%20Bridge%20Metadata%20Tools) tool, I am able to read / write some IPTC creator / rights metadata on my .png files. 
Is there any way for me to get these values using this metadata-extractor package?

**Comment by drewnoakes** [comment]
Not currently, but it should be possible to add it without too much fuss. Can you provide a sample PNG file that contains IPTC data please? The image can be of whatever, but make sure you're permitted to release it for public use without restriction.

There's no standard for IPTC in PNG, but apparently it can be found sometimes in `zTXt` PNG chunks. With a sample image we can take a deeper look.

**Comment by drewnoakes** [comment]
I should point out that PNG does support XMP, so it's probable that Bridge is using XMP to store the IPTC fields. If that's the case, then yes metadata-extractor will work.

**Comment by MadsSwensson** [comment]
[Here](https://user-images.githubusercontent.com/23237075/28418104-d843b0fa-6d5a-11e7-8be9-be9a7c7f530b.png) is a sample photo with [values](https://user-images.githubusercontent.com/23237075/28418392-d26dd916-6d5b-11e7-9769-9e746e6ae6d6.png) in some creator / rights field

**Comment by MadsSwensson** [comment]
Any news on this so far?

**Comment by MadsSwensson** [comment]
I've now seen what you meant by the XMP, the info lies there, thanks for the help!
