### ISSUE TITLE
An error while cloning the project local repository by MSVS or GitHub Desktop

### ISSUE THREAD

**Issue by VictorLoktev** [drewnoakes/metadata-extractor-dotnet#112]
I have made a fork of the project https://github.com/drewnoakes/metadata-extractor-dotnet
to my https://github.com/VictorLoktev/metadata-extractor-dotnet
In MSVS I do Clone to "Local Git Repositories". An error occurs while cloning: 
[git fail.log](https://github.com/drewnoakes/metadata-extractor-dotnet/files/1558219/git.fail.log)
The same error I have if clone of https://github.com/drewnoakes/metadata-extractor-dotnet directly
I can do clone in MSVS of https://github.com/monostream/metadata-extractor-dotnet without any error: 
[git success.log](https://github.com/drewnoakes/metadata-extractor-dotnet/files/1558224/git.success.log)

Using GitHub desktop to make local clone gives an error: "A submodule points to a commit which does not exist." Log file contains errors like this:
Server does not allow request for unadvertised object eb7ccb831febb93153c44e76cdd99b6fd9014353
Fetched in submodule path 'wiki', but it did not contain eb7ccb831febb93153c44e76cdd99b6fd9014353. Direct fetching of that commit failed.

I contacted GitHub team. The team suggested me to open an Issue.
Please help me join the project team.

**Comment by drewnoakes** [comment]
Hi Victor. Thanks for taking the time to report the issue. It's my fault -- I made a mistake somewhere along the line with the wiki submodule. I believe it's fixed now.

```
$ git clone --recurse-submodules git@github.com:drewnoakes/metadata-extractor-dotnet.git
Cloning into 'metadata-extractor-dotnet'...
remote: Counting objects: 16581, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 16581 (delta 9), reused 12 (delta 5), pack-reused 16561
Receiving objects: 100% (16581/16581), 7.05 MiB | 31.00 KiB/s, done.
Resolving deltas: 100% (12909/12909), done.
Submodule 'wiki' (https://github.com/drewnoakes/metadata-extractor.wiki) registered for path 'wiki'
Submodule 'wiki-images' (https://github.com/drewnoakes/metadata-extractor-images.wiki.git) registered for path 'wiki-images'
Cloning into 'C:/Users/Drew/tmp2/metadata-extractor-dotnet/wiki'...
remote: Counting objects: 442, done.
remote: Total 442 (delta 0), reused 0 (delta 0), pack-reused 442
Receiving objects: 100% (442/442), 14.38 MiB | 581.00 KiB/s, done.
Resolving deltas: 100% (257/257), done.
Cloning into 'C:/Users/Drew/tmp2/metadata-extractor-dotnet/wiki-images'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Submodule path 'wiki': checked out '4fb4bddf56247f14d232bd200707d47f36e491cc'
Submodule path 'wiki-images': checked out '637fc76c9de2e1364b2cf4829ce5c0666d54bf8d'
```
