### ISSUE TITLE
XMP parsing fails

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#12]
```
[ERROR: Xmp] Error processing XMP data: Empty schema namespace URI
```

**Comment by kwhopper** [comment]
How was this error generated? Was there a particular XMP used?

**Comment by drewnoakes** [comment]
It's direct output of the [xmp-core-dotnet](https://github.com/drewnoakes/xmp-core-dotnet) library, so the defect really belongs there. That lib is a port of Adobe's XmpCore Java library and apparently has one or more bugs.

**Comment by kwhopper** [comment]
Is this still an issue with the latest push to xmp-core-dotnet?

**Comment by drewnoakes** [comment]
You're right. This appears to have been addressed. Thanks!
