### ISSUE TITLE
Broken metadata segment

### ISSUE THREAD

**Issue by pitr555** [drewnoakes/metadata-extractor-dotnet#134]
Hi, I am using this library to fetch image dimensions from the stream. Recently I've run into an issue with probably broken JPG image. 

There is null value inside the second XMP segment
`<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.5-c002 1.148022, 2012/07/15-18:06:45        "><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> ...... 
NULL byte here 
.....
</x:xmpmeta>
`

and ReadMetadata throws "Unsupported Encoding" exception

I there any way to skip those broken segments? I just want to use available dimensions metadata.

**Comment by kwhopper** [comment]
Is there a link to the image so we can check it out? I have an unpublished fix for some specific null byte issues in XML segments but maybe yours is a different variety.

**Comment by drewnoakes** [comment]
@pitr555 can you share an image that reproduces this issue please?

**Comment by kwhopper** [comment]
Closing for now. Reopen if there is still an issue we can address.
