### ISSUE TITLE
DirectoryExtensions.TryGetDateTime() fails in some cultures

### ISSUE THREAD

**Issue by twest820** [drewnoakes/metadata-extractor-dotnet#138]
Issue is this function calls [DateTime.TryParseExact()](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tryparseexact?view=netframework-4.7.2#System_DateTime_TryParseExact_System_String_System_String___System_IFormatProvider_System_Globalization_DateTimeStyles_System_DateTime__) with a null format provider. The parse therefore can only succeed if the current culture uses the same separators as the file containing the metadata. From a quick review it looks to me like the intent is to perform invariant parsing, in which case the fix would be to pass CultureInfo.InvariantCulture rather than null.

Workaround is to reimplement the method's code. Personally, I hit this on Arabic so setting CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("ar") on a test thread should provide repro.

**Comment by drewnoakes** [comment]
On the general topic of locale sensitivity, we should enable and review these diagnostics:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/9789ad9dc81c13f1ebdac48c5a9a847213269534/.editorconfig#L225-L228
