### ISSUE TITLE
Ignore non jpg- files

### ISSUE THREAD

**Issue by tim19951** [drewnoakes/metadata-extractor-dotnet#139]
Hey everybody,

i use the metadata extractor like : [https://github.com/drewnoakes/metadata-extractor-dotnet/blob/master/MetadataExtractor.Samples/Program.cs](url)
 to read out a lot of metadata of pictures out of different folders, but have an actual problem. 

Even when there is an other datatype than .jpg, it doesn´t works anylonger. e.g .txt 
So is it possible to ignore all different datatypes ? 
And how ?

First idea was something like this:

`var directories1 = JpegMetadataReader.ReadMetadata((fi.FullName).EndsWith(".jpg"));`

Hope for some help. 

Best regards.

**Comment by drewnoakes** [comment]
You can use the [`FileTypeDetector`](https://github.com/drewnoakes/metadata-extractor-dotnet/blob/master/MetadataExtractor/Util/FileTypeDetector.cs) to identify file formats, however you could also just wrap the read call in a try/catch.
