### ISSUE TITLE
rotation missing from quicktime metadata

### ISSUE THREAD

**Issue by copenhaverjf** [drewnoakes/metadata-extractor-dotnet#149]
Hi,
Just like the issue that was patched with the java metadata-extractor library (https://github.com/payton/metadata-extractor/commit/69bb1baacc3faa9c9088b68c3445c65162b8ae2b) I realized through use that rotation is not supported in this library. I assume that the calculation would be similar (ie using the transformation matrix to compute the rotation value in the QuicktimeMetadataReader class)? I have an implementation, but I'm not getting the expected rotation values, so obviously I don't want to create a pull request from it. I'm on the right track though, correct?

**Comment by drewnoakes** [comment]
There's nothing wrong with creating a pull request that's incomplete. You can add WIP in the title to communicate it's incomplete.

**Comment by markegorman** [comment]
What do I do with that

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by drewnoakes** [comment]
@markegorman I don't understand what you're asking, sorry.
