### ISSUE TITLE
can't use nuget install for 4.7.2 target framework

### ISSUE THREAD

**Issue by segfahlt** [drewnoakes/metadata-extractor-dotnet#150]
I'm trying to reference MetadataExtractor in a .Net 4.7.2 Windows Forms app (VS2017 Enterprise).  When using Nuget, it looks like it's failing when it's trying to get XmpCore 5.1.3.

NOTE: I also could not find the package via Extensions and Updates.

Not a deal breaker for me as I was able to pull down the code and build locally, but thought somebody should know. 

<pre>
PM> install-package MetadataExtractor

Attempting to gather dependency information for package 'MetadataExtractor.2.0.0' with respect to project 'ImageManager', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 11.11 sec
Attempting to resolve dependencies for package 'MetadataExtractor.2.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'MetadataExtractor.2.0.0'
Resolved actions to install package 'MetadataExtractor.2.0.0'
Retrieving package 'MetadataExtractor 2.0.0' from 'nuget.org'.
Retrieving package 'XmpCore 5.1.3' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/metadataextractor/2.0.0/metadataextractor.2.0.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/metadataextractor/2.0.0/metadataextractor.2.0.0.nupkg 454ms
Installing MetadataExtractor 2.0.0.
  OK https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg 517ms
Installing XmpCore 5.1.3.
Error downloading 'MetadataExtractor.2.0.0 : XmpCore [5.1.3, )' from 'https://api.nuget.org/v3-flatcontainer/metadataextractor/2.0.0/metadataextractor.2.0.0.nupkg'.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
  GET https://api.nuget.org/v3-flatcontainer/metadataextractor/2.0.0/metadataextractor.2.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/metadataextractor/2.0.0/metadataextractor.2.0.0.nupkg 407ms
Installing MetadataExtractor 2.0.0.
Error downloading 'XmpCore.5.1.3' from 'https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg'.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
  GET https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg
Error downloading 'XmpCore.5.1.3' from 'https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 152.199.4.33:443
  GET https://api.nuget.org/v3-flatcontainer/xmpcore/5.1.3/xmpcore.5.1.3.nupkg
Install failed. Rolling back...
Package 'XmpCore.5.1.3' does not exist in project 'ImageManager'
Package 'XmpCore.5.1.3' does not exist in folder 'g:\development\ImageManager\packages'
Executing nuget actions took 1.83 min
install-package : Unable to find package 'MetadataExtractor' at source ''.
At line:1 char:1
+ install-package MetadataExtractor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:02:05.2617173
PM> 
</pre>

**Comment by drewnoakes** [comment]
That log makes it look like you had a network issue when downloading the xmpcore dependency. Can you try again?

**Comment by segfahlt** [comment]
I would say you are correct. Can't believe I didn't catch that the first time.  I just tried again and it worked fine.

closing.
