### ISSUE TITLE
Error processing XMP data: Unsupported Encoding

### ISSUE THREAD

**Issue by SimonKravis** [drewnoakes/metadata-extractor-dotnet#154]
Error processing XMP data: Unsupported Encoding
![p1040071](https://user-images.githubusercontent.com/8662136/51884896-3d051a80-23dd-11e9-9e58-3bab809fd73b.jpg)
 error when trying to get metadata from attached image

**Comment by drewnoakes** [comment]
@SimonKravis thank you for the sample image. The bug is fixed on `master`. I hope to get a release out soon but can't commit to a date. You can always build the code yourself in the mean time.

**Comment by SimonKravis** [comment]
I can only build the downloaded code on VS 2017, and when i try build MetdataExtractor I get 56 errors like " The type or namespace {SerializableAttribute,Serializable,Serialization,StreamingContext]}  could not be found. Are you missing a using directive or an assembly reference".. All the offending  statements are within #IF !NETSTANDARD1_3 statements, and the Conditional Compilation Symbols on the Build tab of MetadataExtractor project properties is set to NETSTANDARD1_3 so I don't undertstand why they are being flagged. The Project for the error message is MetadataExtractor(netstandard2.0), but the target framework is greyed out in the Application tab of the Project properties. The NetStandard.Library in Dependencies>SDK>has a version number of 1.61.

Can you tell me what to do in order to build MetadataExtractor?

**Comment by drewnoakes** [comment]
@SimonKravis do you see those errors when building in VS? Did you do a package restore first?

If you're still seeing errors, can you include the contents of the Output window here please?

**Comment by SimonKravis** [comment]
Yes, building in VS 2017 Community Edition on Win 7. The Nuget Packages all seemed to restore when I did a clean. Dependencies include an SDK node within which is a NetStandard.Library node  containing many System.xxx entries, including System.Runtime, all with (4.3.0) after them. Output window content attached

**Comment by SimonKravis** [comment]
Not sure if attach worked : Output window content below:
1>------ Build started: Project: MetadataExtractor, Configuration: Debug Any CPU ------
1>MetadataExtractor -> C:\Users\Simon.ALEKATEST.000\Documents\Visual Studio 2017\Projects\MetaDataExtractor\metadata-extractor-dotnet-master\MetadataExtractor\bin\Debug\netstandard1.3\MetadataExtractor.dll
1>Formats\Exif\GpsDirectory.cs(33,1,33,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.'
1>Formats\Exif\GpsDirectory.cs(34,9,34,10): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
1>Formats\Jpeg\JpegProcessingException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>Formats\Png\PngProcessingException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>Formats\Riff\RiffProcessingException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>Formats\Tiff\TiffProcessingException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>ImageProcessingException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>IO\BufferBoundsException.cs(29,22,29,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>MetadataException.cs(27,22,27,35): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
1>IO\BufferBoundsException.cs(39,6,39,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>IO\BufferBoundsException.cs(39,6,39,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>MetadataException.cs(36,6,36,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>MetadataException.cs(36,6,36,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>MetadataException.cs(56,47,56,64): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>MetadataException.cs(56,71,56,87): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>IO\BufferBoundsException.cs(69,51,69,68): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>IO\BufferBoundsException.cs(69,75,69,91): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>ImageProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>ImageProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>ImageProcessingException.cs(56,54,56,71): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>ImageProcessingException.cs(56,78,56,94): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(43,6,43,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(43,6,43,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(44,6,44,19): error CS0246: The type or namespace name 'TypeConverterAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(44,6,44,19): error CS0246: The type or namespace name 'TypeConverter' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegComponent.cs(38,6,38,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegComponent.cs(38,6,38,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngColorType.cs(34,6,34,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngColorType.cs(34,6,34,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngProcessingException.cs(56,52,56,69): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Png\PngProcessingException.cs(56,76,56,92): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Riff\RiffProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Riff\RiffProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Riff\RiffProcessingException.cs(56,53,56,70): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Riff\RiffProcessingException.cs(56,77,56,93): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegProcessingException.cs(36,6,36,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegProcessingException.cs(56,53,56,70): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Jpeg\JpegProcessingException.cs(56,77,56,93): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(328,50,328,63): error CS0246: The type or namespace name 'TypeConverter' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(330,49,330,71): error CS0246: The type or namespace name 'ITypeDescriptorContext' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Tiff\TiffProcessingException.cs(37,6,37,18): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Tiff\TiffProcessingException.cs(37,6,37,18): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(341,48,341,70): error CS0246: The type or namespace name 'ITypeDescriptorContext' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(372,47,372,69): error CS0246: The type or namespace name 'ITypeDescriptorContext' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Tiff\TiffProcessingException.cs(57,53,57,70): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
1>Formats\Tiff\TiffProcessingException.cs(57,77,57,93): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
1>Rational.cs(330,34,330,48): error CS0115: 'Rational.RationalConverter.CanConvertFrom(ITypeDescriptorContext, Type)': no suitable method found to override
1>Rational.cs(341,36,341,47): error CS0115: 'Rational.RationalConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, object)': no suitable method found to override
1>Rational.cs(372,34,372,46): error CS0115: 'Rational.RationalConverter.CanConvertTo(ITypeDescriptorContext, Type)': no suitable method found to override
1>Done building project "MetadataExtractor.csproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by drewnoakes** [comment]
@SimonKravis I can see from that output that you're building the `netstandard1.3` target, which brings in those types via NuGet packages. My assumption is that package restore failed. You can either try restoring packages in VS or on the command line via `nuget restore`.

Can you build the `net45` target?

**Comment by SimonKravis** [comment]
I think the problem is indeed package restore failure. Clicking Update in Nuget shows a lot of error messages. The TagetFramework for MetadataExtractor is greyed out in VS 2017. Editing MetadataExtractor.csproj I find a tag <TargetFrameworks>. Changing the content to net45 from netstandard1.3;netstandard2.0;net35;net45  results in a lot of error messages about projects being incompatible with .net4.6.1

**Comment by drewnoakes** [comment]
> The TagetFramework for MetadataExtractor is greyed out in VS 2017

Can you include a screenshot of what you mean? Is this in the project properties dialog? If so, it's likely that UI only supports single targetting (via `<TargetFramework>`, singular) whereas the project uses multi targetting (via `<TargetFrameworks>`, plural).

> Clicking Update in Nuget shows a lot of error messages

These are probably the real errors. Can you share them?

**Comment by SimonKravis** [comment]
Changing MetadataExtractor.csproj to include <TargetFramework>net45</TargetFramework> instead of multiple frameworks between <TargetFrameworks> and </TargetFrameworks> results in the following messages in ErrorList:
everity	Code	Description	Project	File	Line	Suppression State
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net40 (.NETFramework,Version=v4.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETFramework,Version=v4.0.				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)

**Comment by SimonKravis** [comment]
Changing the <TargetFrameworks> tag to <TargetFramework>  with value net45 enables Framework selection but produces the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net40 (.NETFramework,Version=v4.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETFramework,Version=v4.0.				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)

**Comment by SimonKravis** [comment]
Changing the "TargetFrameworks" tag to TargetFramework with value net45 produced the following errors

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5.				
Error		One or more projects are incompatible with .NETFramework,Version=v3.5 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net40 (.NETFramework,Version=v4.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		One or more projects are incompatible with .NETFramework,Version=v4.0.				
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0 (win7-x86).				
Error		Project MetadataExtractor is not compatible with net35 (.NETFramework,Version=v3.5). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win7-x86. Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)				
Error		Project MetadataExtractor is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project MetadataExtractor supports: net45 (.NETFramework,Version=v4.5)

**Comment by drewnoakes** [comment]
Which project did you do this on? Can you include the screenshot of the greyed out option? I'm not sure why this doesn't build for you.

**Comment by kwhopper** [comment]
@SimonKravis I did a clean install of VS2017 with only the ".NET desktop development" Workload selected leaving the defaults checked in Installation details. This caused a similar error when I tried to build the MetadataExtractor solution. Since this project requires .NET Standard, you have to also install at least ".NET Core 2.0 development tools" from that same Installation details list:

![image](https://user-images.githubusercontent.com/16009408/54851794-0fd83880-4cb9-11e9-8a04-219fa241f634.png)

After that was installed, the project built successfully. Maybe try to install that, undo any project changes you made, then do a build. If that doesn't fix it or if you were getting a different error let us know. Thanks

**Comment by SimonKravis** [comment]
Thanks kwhopper. I uninstalled and re-installed VS Community 2017 with .Net Core 2.0 Development tools checked and the project now builds OK. I'm surprised I haven't struck this problem before as I download and build a lot of VS C# projects. I hope the issue and fix get more widely known.

**Comment by SimonKravis** [comment]
Problems are not over yet - copying the built MetadataExtractor.dll and other files in the net45 folder from the machine with VS Community 2017 to my dev machine with VS 2013 I find I cannot add the new MetadataExtractor.dll as a reference in my application. I get the message "A reference to C:\<new path>\MetadataExtractor.dll cannot be added." Both the new MetadataExtractor.dll which I have built and the old one (which I can add successfully) have .NetFramework 4.5 as the target. The application is built using .Net 4.6.1 as the target framework

**Comment by drewnoakes** [comment]
@kwhopper thank you for your insight here! I'll be sure to include this information in the README to help others in future.

@SimonKravis is that the only error message you get? How are you adding the reference to the project? You might also need to copy the XmlCore DLL.

**Comment by SimonKravis** [comment]
I included XmpCore.dll in the same folder as MetadataExtractor.dll and got the same error.  I'm adding the reference via Add Reference.. from right-click on my application References list.
