### ISSUE TITLE
Tag 2 cannot be converted to Int64.  It is of type System.Int64 with value: 19256142848

### ISSUE THREAD

**Issue by GrumpyMeow** [drewnoakes/metadata-extractor-dotnet#157]
MetadataExtractor.MetadataException
  HResult=0x80131500
  Message=Tag 2 cannot be converted to Int64.  It is of type System.Int64 with value: 19256142848
  Source=MetadataExtractor
  StackTrace:
   at MetadataExtractor.DirectoryExtensions.ThrowValueNotPossible[T](Directory directory, Int32 tagType)
   at MetadataExtractor.DirectoryExtensions.GetInt64(Directory directory, Int32 tagType)
   at Test.Program.GetTagValue(Directory directory, Tag tag) in

**Comment by kwhopper** [comment]
Could you share the image that caused this error? Thanks

**Comment by GrumpyMeow** [comment]
I'm unable to upload the image, because it is such a large file. The file is 19256142848 bytes big.
It's an avi file with the size of 17,9Gigabyte.

**Comment by drewnoakes** [comment]
Thank you for the error report. The error message is self-contradictory. There's a bug in `GetInt64`:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/ef5c8d685ec25f8d0a5794f7245c92b71c62ee51/MetadataExtractor/DirectoryExtensions.cs#L248-L254

It should be calling `TryGetInt64`. A fix is in #161.
