### ISSUE TITLE
time zone offset support

### ISSUE THREAD

**Issue by m5x** [drewnoakes/metadata-extractor-dotnet#158]
There seems to be missing tags 0x9010-0x9012 called OffsetTime, OffsetTimeOriginal and OffsetTimeDigitized in ExifDirectoryBase. Is this intentional and time-zone adjustment is performed internally by the library or time zones are not supported for date/times?

**Comment by drewnoakes** [comment]
The library doesn't perform any time zone adjustments. In general values are returned exactly as they're found in the file itself.

It looks like these tags should be added. Could you submit a PR?

**Comment by patricksadowski** [comment]
This was already resolved by #223.

**Comment by drewnoakes** [comment]
@patricksadowski thanks very much.
