### ISSUE TITLE
Port XMP ancestor node limit from Java library

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#162]
We need to port the change in drewnoakes/metadata-extractor#394 to this library.

**Comment by kwhopper** [comment]
This isn't possible in 5.1.3 of XmpCore. The project will need to reference the newer 6.1.10 port. Thanks

**Comment by markegorman** [comment]
How do I view these codes I don’t wana mess up any work
I’m sorry I’m new to all this and have nooo idea what I’m doin please bear with me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kwhopper** [comment]
[https://github.com/drewnoakes/xmp-core-dotnet](https://github.com/drewnoakes/xmp-core-dotnet)

@drewnoakes might be prepping the XmpCore project for a new release. There isn't much to do on this issue until that is complete.

**Comment by drewnoakes** [comment]
Fixed by @kwhopper in #394.
