### ISSUE TITLE
No method to SET GPS coordinates

### ISSUE THREAD

**Issue by lordofscripts** [drewnoakes/metadata-extractor-dotnet#163]
The  class has a GetGeoLocation method but there is no counterpart to set the metadata. For example, if in my application I want to alter the Latitude/Longitude of the media file. I am really missing that functionality.

Also, in exploring photo files I noticed that some photos had a GPS Directory but no coordinates (lat/lng), in such cases only the GPS Version tag was present in the directory. So, when I was truly only interested in getting the lat/lng, I had to write extra code to check that not only it had the GPSDirectory but also contained the Latitude/Longitude tags as well.

**Comment by drewnoakes** [comment]
> The class has a GetGeoLocation method but there is no counterpart to set the metadata. For example, if in my application I want to alter the Latitude/Longitude of the media file. I am really missing that functionality.

The library does not support modifying metadata in images. See #23.

> Also, in exploring photo files I noticed that some photos had a GPS Directory but no coordinates (lat/lng), in such cases only the GPS Version tag was present in the directory. So, when I was truly only interested in getting the lat/lng, I had to write extra code to check that not only it had the GPSDirectory but also contained the Latitude/Longitude tags as well.

Images can provide empty directories. In general there's no guarantee that an image provides any given tag, so you should always handle the case that the value you want is not present.
