### ISSUE TITLE
Create a new release soon?

### ISSUE THREAD

**Issue by twtduck** [drewnoakes/metadata-extractor-dotnet#165]
It's been a couple years since a release, and there are some newer features that I use regularly. Are there plans to create a new release soon? 

Cordially,
Thomas

**Comment by drewnoakes** [comment]
Thanks everyone for your patience.

https://www.nuget.org/packages/MetadataExtractor/2.1.0

**Comment by drewnoakes** [comment]
https://github.com/drewnoakes/metadata-extractor-dotnet/releases/tag/2.1.0

**Comment by drewnoakes** [comment]
Please let me know asap if you encounter any issues with the new release. Thanks.

**Comment by twtduck** [comment]
Will do; thanks!
