### ISSUE TITLE
DateTime test

### ISSUE THREAD

**Issue by dvigor** [drewnoakes/metadata-extractor-dotnet#172]
Hi, 
string strDateTime = ExifIfd0Directory?.GetString(ExifDirectoryBase.TagDateTime);

returns: 2017:02:24 21:02:91
Explorer shows: 05.01.2017 19:25

Test project and pictures attached.

Thank.
[DataTime.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/3290606/DataTime.zip)
[Images.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/3290608/Images.zip)

**Comment by drewnoakes** [comment]
There are several time tags on `ExifDirectoryBase`. Please test with all of them, or dump all tags to see whether a different tag matches what you're seeing in Explorer. If you cannot find the same date anywhere, please comment here and I'll reopen this issue. Thanks.

**Comment by dvigor** [comment]
Tags "TagDateTimeDigitized" and "TagDateTimeOriginal" - is null.

**Comment by drewnoakes** [comment]
If you dump all tags, do you see the expected date anywhere?

**Comment by dvigor** [comment]
Is there a quick way to get all the tags at once?

**Comment by drewnoakes** [comment]
```c#
var directories = ImageMetadataReader.ReadMetadata(...);

foreach (var directory in directories)
    foreach (var tag in directory.Tags)
        Console.WriteLine(tag);
```

**Comment by dvigor** [comment]
Thanks, all worked well. It seems that the best date to take from Exif SubIFD\TagDateTimeOriginal.
