### ISSUE TITLE
Support GPS from MP4

### ISSUE THREAD

**Issue by Zeleksonob** [drewnoakes/metadata-extractor-dotnet#192]
Can you please provide an example how to extract EXIF from mp4 file?

**Comment by drewnoakes** [comment]
Running the sample shown in the README against your file will pull all currently supported metadata from the media:

https://github.com/drewnoakes/metadata-extractor-dotnet#usage

**Comment by Zeleksonob** [comment]
@drewnoakes 
following your suggestion 
the output was :
![header](https://user-images.githubusercontent.com/7282333/61722119-67270c00-ad72-11e9-9ed6-6925bba7e17b.PNG)


when i am using exififtool :

![exitif](https://user-images.githubusercontent.com/7282333/61722337-c5ec8580-ad72-11e9-95bc-c99b1367bc53.PNG)

**Comment by drewnoakes** [comment]
Are you able to contribute a small MOV file to the project that includes GPS data? Without sample data we are unable to verify any change is correct. Note that any file you contribute would be publicly available, so please ensure you're happy with whatever data is in that file.

**Comment by Zeleksonob** [comment]
@drewnoakes 

sure no problem : 
[https://drive.google.com/open?id=1FVe6Tv_nZI-yrB7AbgevRoRlLoUb95AW](url)

**Comment by drewnoakes** [comment]
Thank you for the file! I've added it to the sample library we use for testing and development. It'll be very helpful in getting support for GPS data into the library.

**Comment by Zeleksonob** [comment]
@drewnoakes 
do you think it will happened any time in  the near future ?

**Comment by drewnoakes** [comment]
@Zeleksonob I have no idea what's involved for this one. Usually features like this are added by users who want the feature badly enough to implement it themselves and contribute it to the project. The good news in this case is that APIs for dealing with the basic structures of a MOV file already exist, so it should be a relatively simple matter of parsing a single chunk (atom, IIRC) of the data. If you wanted to take a stab at it I'm sure we'd be able to help point you in the right directly.

**Comment by d5smith** [comment]
Hi, I was also in need of this functionality so I gave it a shot. 
Solution also addresses issue #234 
It was a little tricky because the keys and the values are in different Atoms.
I had to introduce 2 static fields to hold xref data which would mean parsing of this specific data is not thread safe.
Best way to share? Just create a pull request? Then you can decide if any is worth keeping?
Thanks. Cheers.

**Comment by kwhopper** [comment]
A pull request would be the best way. Thanks

**Comment by d5smith** [comment]
I put up PR #240 - 
I addressed PR feedback in a follow-on PR #241 so as to not add test file to repo history.
Let me know if there's anything else you need. Thanks.

**Comment by drewnoakes** [comment]
> Let me know if there's anything else you need

I just need the free time to pick it up again 😃 Sorry for the delay.
