### ISSUE TITLE
Not able to read XMP Description from PNG file

### ISSUE THREAD

**Issue by marcin2x** [drewnoakes/metadata-extractor-dotnet#204]
We are not able to read XMP meta from some PNG files. 
It's displayed on http://exif.regex.info/exif.cgi, but i don't get it using ImageMetadataReader.ReadMetadata.
Here is the image:
![07300021234228 1](https://user-images.githubusercontent.com/14849124/64328244-64ecda00-cfcd-11e9-9466-885102997aa5.png)
Here is metadata displayed on website:
![image](https://user-images.githubusercontent.com/14849124/64328298-7d5cf480-cfcd-11e9-9e3a-872838fdf2c9.png)

I've tried latest version of library (from master branch).

Could you help and verify whether it's a bug in library or issue with metadata?

**Comment by drewnoakes** [comment]
Thank you for the error report and sample image. A fix for this is available in #209 and will be part of the next release.
