### ISSUE TITLE
Reading IPTC tag Program Version as formatted string

### ISSUE THREAD

**Issue by r-e-n-e-g-i** [drewnoakes/metadata-extractor-dotnet#214]
Hi, after reading the IPTC tag Program Version, the result is 12846 instead of 2.2.2 (even when using GetDescription()). Is there any way to get the formatted string instead of an int value?

**Comment by drewnoakes** [comment]
There's not enough info here to help. What is your code? Can you share an image?

**Comment by r-e-n-e-g-i** [comment]
Thank you for your fast response. I have attached an DCR file with this problem.

[Kodak DCS Pro SLRn - Raw.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/3600848/Kodak.DCS.Pro.SLRn.-.Raw.zip)

The code looks as follows:
`                if (directories.OfType<IptcDirectory>().FirstOrDefault() is IptcDirectory iptcDirectory)
                {
                    result.ProgramVersion = iptcDirectory.HasTagName(IptcDirectory.TagProgramVersion) ? iptcDirectory.GetString(IptcDirectory.TagProgramVersion) ?? "" : "";
                }`

**Comment by drewnoakes** [comment]
I can see `2.2.2` in the file's bytes:

![image](https://user-images.githubusercontent.com/350947/64743143-029e5700-d542-11e9-96a5-def1d603fb77.png)

There's special handling for various version values that appear as two or more bytes:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/3b59085ff36600baf9db05c41909dad3d3f7d2af/MetadataExtractor/Formats/Iptc/IptcReader.cs#L200-L211

The 12846 value is the first two bytes (0x322e). Probably the library should not be reading only two bytes for a version number if the tag has more than two. If I change the `>=` to `==` then `2.2.2` is returned.

I'll do some testing to see whether this fix breaks other images.

Are you able to donate this sample to the project? We do not currently have any DCR files so it would be good to have one for testing purposes and to catch bugs like this.

---

As an aside, that file also produces an error:

```
ERROR: Invalid IPTC tag marker at offset 459. Expected '0x1c' but got '0x0'.
```

This is unrelated and may be an example of https://github.com/drewnoakes/metadata-extractor/issues/122.

**Comment by drewnoakes** [comment]
Changing the comparison from `>=` to `==` fixes two other cases in the sample image library and breaks none!

```diff
diff --git a/jpg/metadata/dotnet/Issue 80.jpg.txt b/jpg/metadata/dotnet/Issue 80.jpg.txt
index 3190e90..540d021 100644
--- a/jpg/metadata/dotnet/Issue 80.jpg.txt
+++ b/jpg/metadata/dotnet/Issue 80.jpg.txt
@@ -282,7 +282,7 @@ TYPE: JPEG
 [IPTC - 0x0237] Date Created = 2008:03:14
 [IPTC - 0x023c] Time Created = 135926.054-0600
 [IPTC - 0x0241] Originating Program = IDimager V5 - Digital Image Manager
-[IPTC - 0x0246] Program Version = 13614
+[IPTC - 0x0246] Program Version = 5.1.3.6-ProSL
 [IPTC - 0x0250] By-line = Corbis
 [IPTC - 0x0274] Copyright Notice = © Corbis.  All Rights Reserved.

diff --git a/tif/ImageTestSuite/metadata/dotnet/221209eb0a273029efa18f4c61f6628a.tif.txt b/tif/ImageTestSuite/metadata/dotnet/221209eb0a273029efa18f4c61f6628a.tif.txt
index 965d60f..6eefa13 100644
--- a/tif/ImageTestSuite/metadata/dotnet/221209eb0a273029efa18f4c61f6628a.tif.txt
+++ b/tif/ImageTestSuite/metadata/dotnet/221209eb0a273029efa18f4c61f6628a.tif.txt
@@ -23,7 +23,7 @@ TYPE: TIFF

 [IPTC - 0x015a] Coded Character Set = UTF-8
 [IPTC - 0x0200] Application Record Version = 2
-[IPTC - 0x0246] Program Version = 20585
+[IPTC - 0x0246] Program Version = Pixelmator 1.1.4
[Exif SubIFD - 0xa001] Color Space = sRGB
[Exif SubIFD - 0xa002] Exif Image Width = 500 pixels
```

**Comment by drewnoakes** [comment]
Thanks for the report.

Reiterating from above, for visibility:

> Are you able to donate this sample image to the project? We do not currently have any DCR files so it would be good to have one for testing purposes and to catch bugs like this.

**Comment by r-e-n-e-g-i** [comment]
Thank you for the support and yes, you are welcome to use the picture for testing purposes.

 

Best regards

Rene

 

Von: Drew Noakes <notifications@github.com> 
Gesendet: Donnerstag, 12. September 2019 04:18
An: drewnoakes/metadata-extractor-dotnet <metadata-extractor-dotnet@noreply.github.com>
Cc: r-e-n-e-g-i <rene@gillmeister.email>; Author <author@noreply.github.com>
Betreff: Re: [drewnoakes/metadata-extractor-dotnet] Reading IPTC tag Program Version as formatted string (#214)

 

Thanks for the report.

Reiterating from above, for visibility:

Are you able to donate this sample image to the project? We do not currently have any DCR files so it would be good to have one for testing purposes and to catch bugs like this.

**Comment by r-e-n-e-g-i** [comment]
Thank you for the support and yes, you are welcome to use the picture for testing purposes.
