### ISSUE TITLE
Quicktime Metadata - missing data

### ISSUE THREAD

**Issue by DHitchenUK** [drewnoakes/metadata-extractor-dotnet#234]
Hi, I'm looking at the metadata in a quicktime file, and wondering how to get access to all the missing values. For example.

IMG_0270.mov from iPhone contains data such as the camera, creation date, GPS values etc. However the data from metadata-extractor is missing those values (and the tags).

I can provide an example file and the metadata I know to exist if that helps?

Thanks

**Comment by drewnoakes** [comment]
Thanks for your issue. It seems related to #192. Having more sample files is always useful. Can you get one that's as small (in bytes) as possible?

**Comment by DHitchenUK** [comment]
I've attached a file, specifically missing that i've noticed are these tags that exist within the file.
For example, current the date created is 2019, but actually the date is 2018 as shown here from exiftool.

Make                            : Apple
Model                           : iPhone X
Software                        : 11.3
Creation Date                   : 2018:04:06 17:26:41+01:00

[IMG_0270(1).zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/3854259/IMG_0270.1.zip)

If you can all the metadata working and post an amazon shopping list (I've donated to others who do that) then I'm happy to donate in that way.

**Comment by DHitchenUK** [comment]
The tag that hold the correct created date is "com.apple.quicktime.creationdate"

**Comment by drewnoakes** [comment]
@DHitchenUK the library now extracts a bunch of metadata from your media. See:

https://github.com/drewnoakes/metadata-extractor-images/blob/master/mov/metadata/dotnet/Issue%20234%20dotnet.mov.txt

Thanks to @d5smith for making this happen.
