### ISSUE TITLE
PCL Support

### ISSUE THREAD

**Issue by ravensorb** [drewnoakes/metadata-extractor-dotnet#24]
Any thought to adding support for other platforms (like iOS and Android or even better PCL)?

**Comment by drewnoakes** [comment]
That sounds great. Do you know what's required for these platforms? I have
no relevant experience myself.

**Comment by ravensorb** [comment]
I did a bit of research and for the most part converting the library over should be easy with 1 exception -- XMP library that is being referenced is not PCL compatible.  I took a look at that library and it actually would not be too hard to convert as all that is needed is to switch from using System.Xml to System.Linq (XmlNode to XNode) and than it is fully PCL compatible.

**Comment by drewnoakes** [comment]
The XMP library has been a source of many challenges for years in the Java version. I'm inclined to make it an optional dependency somehow, maybe through a plugin architecture.

As for iOS/Android, is there anything required beyond being a PCL library?

**Comment by ravensorb** [comment]
I like the plugin in architecture -- maybe using DI/IoC?  And no, as long as the library is "porrtable" it works with Xamarin and as a result works with iOS/Android (As well as any other platform that supports .NET core -- like Windows IoT).

**Comment by drewnoakes** [comment]
The simplest thing would be to create a PCL build that initially excludes
XMP support using #if PCL ... #endif

Later, if the XMP library becomes PCL compatible, it could be reintroduced.

**Comment by drewnoakes** [comment]
Looking at this a little today I found a few challenges to porting. Nothing insurmountable, but they increase the time required to support PCL.

The following types are not available, but are used:

* `Encoding.ASCII` (use `Encoding.UTF8` instead?)
* `FileStream` (remove these APIs and only accept `Stream`?)
* `[Serializable]` and `SerializationInfo` (remove this)
* `IReadOnlyList<T>` (fall back to `IList<T>` as done in the NET35 build)
* `Console` (`Debug.WriteLine` instead?)
* `System.IO.Compression.DeflateStream` (use [this](https://www.nuget.org/packages/Microsoft.Bcl.Compression)?)

Also `Encoding.GetString(byte[])` doesn't exist, but is trivially satisfied by adding `offset` and `length` parameters.

**Comment by drewnoakes** [comment]
Also `FileMetadataReader` has to go, as PCL has no abstraction of file systems, as far as I can tell.

**Comment by drewnoakes** [comment]
Some work on the `pcl` branch. Pending are `Console`, `DeflateStream` and `Encoding.ASCII`. And of course, testing.

**Comment by drewnoakes** [comment]
The `pcl` branch is now building a portable DLL of the library too.

This still needs some testing before being released.

**Comment by drewnoakes** [comment]
@ravensorb can you test this PCL build please?

https://www.nuget.org/packages/MetadataExtractor.Portable/

You'll need to take `MetadataExtractor.Portable` version `1.1.1-beta2`.

**Comment by drewnoakes** [comment]
@ravensorb or @black78, would you have time to check the PCL version of this lib, available via NuGet?

**Comment by Laodhy** [comment]
I've try to import your lib in my Xamarin.forms project, in the PCL, but i have problems to install, i(ve this error message (my traduction from french, sry for broken english) : 

You tried   to install this package in a project who use 
« portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10 », but the package does not contains content file ou assembly reference compatible with this infrastructure. 

French error message : 
Vous essayez d’installer ce package dans un projet ciblant « portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10 », mais le package ne contient aucun fichier de contenu ou référence d’assembly compatible avec cette infrastructure

**Comment by ravensorb** [comment]
@drewnoakes I'll see if I can test this weekend (was a crazy week)

**Comment by drewnoakes** [comment]
@ravensorb, that'd be great.

@Laodhy I'm not familiar with Xamarin.Forms and I don't have much free time for the next few weeks. Hopefully you can investigate what this means, or @ravensorb may do. A pull request would be ideal.

**Comment by ravensorb** [comment]
The issue is the profile that @Laodhy is using (it looks like it is a Windows Phone 8.0 and a Windows Universal App profile).  The current build of the PCL library isn't setup for both.  If I get a chance this weekend, I'll take a look at the nuget package file and see what change we can make to support that profile as well.

**Comment by Laodhy** [comment]
I've tried to install your MetadatExtractor.Portable witch the package manager console, and it's look like the problem come from MonoAndroid version 6.0 : 

Error : You tried to install this package in a project who use MonoAndroid, Version=v6.0, but the package doesn't contain content files or assembly reference compatible with this infrasctrure. 

(Original French)  Impossible d’installer le package «SharpZipLib 0.86.0». Vous essayez d’installer ce package dans un projet ciblant «MonoAndroid,Version=v6.0», 
mais le package ne contient aucun fichier de contenu ou référence d’assembly compatible avec cette infrastructure. 

+ Install-Package MetadataExtractor.Portable -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 

The search continues !

**Comment by ravensorb** [comment]
Looks like xmp-core-dotnet now has a PCL version (https://github.com/drewnoakes/xmp-core-dotnet/issues/4).  Think it makes sense to bring that back in?

**Comment by drewnoakes** [comment]
Please try this beta release and report back on whether it works for you or not: https://www.nuget.org/packages/MetadataExtractor/1.1.1-beta3

**Comment by drewnoakes** [comment]
I believe PCL support is now ready on master, and available via a pre-release NuGet package, so I'll close this now. Please comment or open a new issue if you find this support problematic or lacking in some way.

**Comment by kwhopper** [comment]
I've noticed Silverlight 5 compatibility in the PCL build(s) excludes a good number of .NET classes which makes it more difficult to maintain the PCL if/else blocks. As a small example, Math.Round doesn't have MidpointRounding mode in the overload list. Do you know if anyone is clamoring for Silverlight 5 support in this project? I wonder if it's ok to remove that build target. Silverlight is (I think) no longer actively updated by Microsoft other than maybe security builds. What do you guys think?  Thanks

**Comment by drewnoakes** [comment]
I can see both sides here. It's nice to be as broadly usable as possible.
But if it's limiting what's possible then we could consider removing it.

Are there cases other than numeric rounding? I suppose the rounding mode is
required to give parity with the Java implementation, no? We can aim for
parity on the net45 build, with best-effort parity for other targets.

**Comment by kwhopper** [comment]
This might be a mild overreaction on my part. Rounding mode seemed like such a simple thing that it's strange they wouldn't include it. Maybe shelve this but keep an eye open on which platforms are normally used with this PCL build. I get the feeling very soon .NET core is going to take over, as will Windows 10 for phones. After that happens, Silverlight 5 may be more hindrance than help. Thanks

**Comment by drewnoakes** [comment]
Yes it seems that before too long .NET Core will be more commonplace and
the new .NET Platform Standard will become what we target.

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

Thankfully it's much simpler than PCL profiles.
