### ISSUE TITLE
VS2013 build issues

### ISSUE THREAD

**Issue by kwhopper** [drewnoakes/metadata-extractor-dotnet#25]
Hello. Does building in VS2013 or better require Resharper to be installed? I don't have it and there are all kinds of compilation problems, such as:

Pure]
        public static bool IsValidDate(int year, int month, int day)
            => year >= 1 && year <= 9999 &&
               month >= 1 && month <= 12 &&
               day >= 1 && day <= DateTime.DaysInMonth(year, month);

Thanks

**Comment by drewnoakes** [comment]
The project uses C# 6 language feature so must be built using VS2015. You can use the library from .NET 3.5 or later via the NuGet packages.

There is no need to have ReSharper installed.

**Comment by kwhopper** [comment]
Ok. Thanks!
