### ISSUE TITLE
Long Title from jpeg Truncated

### ISSUE THREAD

**Issue by cmiles** [drewnoakes/metadata-extractor-dotnet#253]
ExifTool and Windows File Properties report the Title of the included image as "2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walcott Peak in the Background" - this is the value I expected based on the title entered into Lightroom. The relevant line from ExifTool output:

Title: 2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walcott Peak in the Background

However the data I am seeing from metadata-extractor appears to truncate the Title:

517 | IPTC | Object Name | "2020 05 Blooming Paloverde and Saguaros with Ragged Top and Walc"

Notes:
 - I have at least one other example of this behavior
 - These files are exports from Lightroom 9.2.1
 - .NET Core 3.1.300-preview-015135
 - MetadataExtractor from nuget version 2.4.0
 - Could be related to #308 - I haven't dug into the details enough to say, although would note related to that discussion that while the format here could well be technically incorrect Lightroom producing it might make it more worth working around?
 - BitmapSource BitmapMetadata Title shows the complete/correct Title.

![2020-05-Blooming-Paloverde-and-Saguaros-with-Ragged-Top-and-Walcott-Peak-in-the-Background](https://user-images.githubusercontent.com/15463/81426731-76fbbb00-910e-11ea-9219-15bc38a40b1f.jpg)

**Comment by paperboyo** [comment]
See https://github.com/drewnoakes/metadata-extractor/issues/474#issuecomment-626014133.

**Comment by cmiles** [comment]
Thanks @paperboyo - that was exactly what I needed - because all tests had been with shorter titles I had never thought about/realized that the Title would be written differently into IPTC and XMP, obvious now that I see it! Thanks again for comment and information!!!
