### ISSUE TITLE
How to create Xmp file?

### ISSUE THREAD

**Issue by ju2pom** [drewnoakes/metadata-extractor-dotnet#254]
Hi,
Thank you for this great library, I already use it to extract metadata from images with success.
Today I'd like to save metadata like keywords or rating to an xmp file (or embedded xmp if possible).
Is it possible to do it with metadata-extractor? I had a look to xmp-core but did not see anything related to write a new xmp file.
If neither metadata-extractor nor xmp-core can do it do you have any hint for me on how to do it?
Thanks.

**Comment by drewnoakes** [comment]
XmpCore supports modifying and writing XMP data, but not back to the original image.
