### ISSUE TITLE
Error when reading .avi file

### ISSUE THREAD

**Issue by tipa** [drewnoakes/metadata-extractor-dotnet#255]
`System.IO.IOException: 'End of data reached.'`
using NuGet package 2.4.1 and this video file: 
[MVI_4823.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/4620971/MVI_4823.zip)

**Comment by drewnoakes** [comment]
@tipa would you give permission to add this file to the test database? Surprisingly we have no `.avi` files at all right now.

**Comment by tipa** [comment]
Yes you can add it to the test database

**Comment by drewnoakes** [comment]
Fixed in b8ecff9ae05ff3714efe51340978cf42a402279a.

**Comment by drewnoakes** [comment]
Released in 2.4.2.

**Comment by tipa** [comment]
Wow - that was fast! 😲 Thanks a lot!
