### ISSUE TITLE
Sample code for XMP

### ISSUE THREAD

**Issue by flemingm** [drewnoakes/metadata-extractor-dotnet#259]
Attached is sample code for accessing XMP data...

Show how to access XMP metadata and use XMP options.

[net3Console XMP sample.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/4810935/net3Console.XMP.sample.zip)

**Comment by drewnoakes** [comment]
Thank you for sharing this.

If you'd like to, please submit a PR to extend the samples in the repo directly: https://github.com/drewnoakes/metadata-extractor-dotnet/tree/master/MetadataExtractor.Samples
