### ISSUE TITLE
GPS location from 'udta'; with code patch

### ISSUE THREAD

**Issue by kirk-marple** [drewnoakes/metadata-extractor-dotnet#261]
We've found that MetadataExtractor isn't seeing GPS location in Android recorded video files.

I've been able to fix it locally, and would like to ask that this be added into the product.

Patch:
`
122a123,139
>             void UserDataHandler(AtomCallbackArgs a)
>             {
>                 switch (a.TypeString)
>                 {
>                     case "?xyz":
>                         var directory = new QuickTimeMetadataHeaderDirectory();
>                         var stringSize = a.Reader.GetUInt16();
>                         var languageCode = a.Reader.GetUInt16();
>                         var stringValue = a.Reader.GetBytes(stringSize);
>                         var s = Encoding.UTF8.GetString(stringValue);
> 
>                         directory.Set(QuickTimeMetadataHeaderDirectory.TagGpsLocation, s);
>                         directories.Add(directory);
>                         break;
>                 }
>             }
> 
249a267,271
>                         break;
>                     }
>                     case "udta":
>                     {
>                         QuickTimeReader.ProcessAtoms(stream, UserDataHandler, a.BytesLeft);
`

**Comment by drewnoakes** [comment]
Thanks for this. Can you create a pull request?

**Comment by kirk-marple** [comment]
Sure thing, PR submitted.

**Comment by drewnoakes** [comment]
This has been fixed. Thanks Kirk for the PR.
