### ISSUE TITLE
Support for dotnet 5.4 runtime

### ISSUE THREAD

**Issue by bravecobra** [drewnoakes/metadata-extractor-dotnet#28]
Can we get support for the dotnet 5.4 runtime through Nuget?

**Comment by drewnoakes** [comment]
I'm not sure which version of .NET you mean. The latest version at present is 4.6.

**Comment by bravecobra** [comment]
I'm talking about the runtime microsoft called vnext. When making a asp.net portable library, that runtime 5.4 is being added, together with 4.6. I want to use this library in an asp.net vnext application, but it doesn't seem to be compatible.

**Comment by drewnoakes** [comment]
Sorry but I'm still not sure what you mean as I'm not that familiar with
modern ASP.NET. Can you show me the error message you're receiving?

You might also try the PCL version of this library.

**Comment by drewnoakes** [comment]
I'm going to close this. Please reopen if you can explain in more detail what you need.
