### ISSUE TITLE
Keyword extraction for PNG files?

### ISSUE THREAD

**Issue by Webreaper** [drewnoakes/metadata-extractor-dotnet#280]
I'm trying to pull the keywords from the attached image. If I run Exiftool, the keywords show up correctly (e.g., 'tree' and 'autumn'). But reading it using the .Net Metadata-Extractor doesn't seem to load the keywords; they're not in the `IptcDirectory`, nor anywhere that I can find. I've trawled through the entire structure and tags in the debugger and can't see any keyword tags anywhere. What am I missing? Are PNG keywords supported?

<img width="320" alt="tree" src="https://user-images.githubusercontent.com/4901102/106536243-f1b40400-64ef-11eb-9552-ced149e87a80.png">

**Comment by drewnoakes** [comment]
Looks like a bug in how we process IPTC data in PNG files. I won't have time to look at it for a while. Would you like to investigate and submit a pull request if you find a fix?

**Comment by Webreaper** [comment]
Might be able to, although wouldn't have the first clue where to start....

**Comment by paperboyo** [comment]
Hey. I’m only a user, so cannot help much! These keywords (to an untrained eye):
- are not read by Adobe or Apple Preview
- all three appear under one heading in exiftool, while new ones are added one-per-heading (see pt. 1 below)
- when added to in exiftool, only the added ones are visible in Adobe/Apple Preview (see pt. 2 below)
- even the added ones are not visible to metadata-extractor (may be that our implementation is to blame, I wouldn’t know!)
- `xmp.dc:subject` equivalent ones added by the `MWG` option by exiftool are visible but not comntain the original ones; the fact that exiftool won’t copy the original ones to `dc:subjects` may provide a pointer (?) – pt. 3 below

1. Original image (`exiftool -v2`):
```
PNG zTXt (113 bytes):
  + [Photoshop directory, 40 bytes]
  | IPTCData (SubDirectory) -->
  | - Tag 0x0404 (28 bytes)
  | + [IPTC directory, 28 bytes]
  | | -- IPTCApplication record --
  | | Keywords = Autumn, tree, le
  | | - Tag 0x0019, IPTCApplication record (16 bytes, string[0,64])
```

2. Added two keywords using `exiftool -use MWG -MWG:Keywords+=""`:
```
PNG zTXt (132 bytes):
  + [Photoshop directory, 64 bytes]
  | IPTCData (SubDirectory) -->
  | - Tag 0x0404 (52 bytes)
  | + [IPTC directory, 52 bytes]
  | | -- IPTCApplication record --
  | | Keywords = Autumn, tree, le
  | | - Tag 0x0019, IPTCApplication record (16 bytes, string[0,64])
  | | ApplicationRecordVersion = 4
  | | - Tag 0x0000, IPTCApplication record (2 bytes, int16u)
  | | Keywords = atari
  | | - Tag 0x0019, IPTCApplication record (5 bytes, string[0,64])
  | | Keywords = commodore
  | | - Tag 0x0019, IPTCApplication record (9 bytes, string[0,64])
```
3. `xmp.dc:subjects` array after adding new ones in pt. 2:
```
PNG iTXt (905 bytes):
  + [XMP directory, 883 bytes]
  | XMPToolkit = Image::ExifTool 12.08
  | Subject = atari
  | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/dc:subject/rdf:Bag/rdf:li 10'
  | Subject = commodore
  | - Tag 'x:xmpmeta/rdf:RDF/rdf:Description/dc:subject/rdf:Bag/rdf:li 11'
```

**Comment by drewnoakes** [comment]
You can stick a breakpoint here:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/427ab46a9293013c418ad32ad4a9400f2edfa060/MetadataExtractor/Formats/Png/PngMetadataReader.cs#L409-L419

If that doesn't get hit for some reason, try here:

https://github.com/drewnoakes/metadata-extractor-dotnet/blob/427ab46a9293013c418ad32ad4a9400f2edfa060/MetadataExtractor/Formats/Png/PngMetadataReader.cs#L224-L255

**Comment by Webreaper** [comment]
Thanks!!
