### ISSUE TITLE
MPEG-2.5 not supported with mp3 files

### ISSUE THREAD

**Issue by MuhamedRaafat** [drewnoakes/metadata-extractor-dotnet#285]
Hello,

when I tried to ReadMetadata of an mp3 file, a **"MPEG-2.5 not supported"** is returned is there any solution to solve this 
problem ?

**Comment by drewnoakes** [comment]
Are you able to publicly provide a sample MP3 file that exhibits this issue? Please ensure it is not copyrighted.

**Comment by MuhamedRaafat** [comment]
Thanks for your reply,

Here is the download link: https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_5MG.mp3

**Comment by drewnoakes** [comment]
@MuhamedRaafat when I run the library on the file you provided, I see a different error:

> EXCEPTION: File format could not be determined

Are you sure that file is producing the same issue you're seeing?

**Comment by MuhamedRaafat** [comment]
@drewnoakes yes I am recieving the same error as your, but when i try to clone the project and run mp3 class manually i have recieved
`MPEG-2.5 not supported`

**Comment by drewnoakes** [comment]
I can't find much information on MPEG-2.5. One source suggests it's an uncommon proprietary format.

My browser is able to play that file just fine, however.

**Comment by MuhamedRaafat** [comment]
So there are no solutions to deal with this issue?

**Comment by drewnoakes** [comment]
This will require someone to spend some time investigating this file's format and putting together a pull request to add support. It may be a small or large change. You are welcome to do this investigation and share your findings or even send a pull request to add this support.

**Comment by drewnoakes** [comment]
@MuhamedRaafat this was addressed by @jbraendle in #314.
