### ISSUE TITLE
[BUG] - OfType<ExifIfd0Directory>().FirstOrDefault() returns null on some specific Android devices

### ISSUE THREAD

**Issue by Brunoporto2702** [drewnoakes/metadata-extractor-dotnet#303]
(Please include as much information as possible, and attach a sample image if possible.)

Hi!

I have implemented this library in order to get Xamarin's MediaPicker library to work properly, once it takes pictures rotated in diferent angles depending on the phone that is running the app. 

```
var meta = ImageMetadataReader.ReadMetadata(await photo.OpenReadAsync());
var subIfd0Directory = meta.OfType<ExifIfd0Directory>().FirstOrDefault();
var orientation = subIfd0Directory?.GetDescription(ExifDirectoryBase.TagOrientation);
var rotationAngle = GetRotationAngle(orientation);
```

Tha problem is pretty straigth forward: on some especific devices e.g. Asus ZenPhoneSelfie, Motorola moto g(8) plus, and Motorola moto g(7) power, the result of the query 

`.OfType<ExifIfd0Directory>().FirstOrDefault()`

returns null and I am unable to get the phone's orientation properly. 

Does someone have any idea how to make it work properly on those devices? 

I do not have access to test devices like the ones that are going through this problem.... 

Cheers!

**Comment by drewnoakes** [comment]
I'll close this for now as we do not yet have evidence of a bug. If you believe a bug exists, please attach an image that demonstrates the problem and we can reopen this. Thanks.
