### ISSUE TITLE
Real PENTAX / RICOH support

### ISSUE THREAD

**Issue by skorpionet100** [drewnoakes/metadata-extractor-dotnet#318]
Hi,

I created this drewnoakes/metadata-extractor-dotnet#319 but I'm not sure that it's the right way to ask for extend the support to exif tags specific by PENTAX / RICOH files.

Thanks.

**Comment by drewnoakes** [comment]
I just transferred that issue to this repo.

Other than that, it contains all the information needed to start the work. It's just a matter of someone picking that work up. If you'd like to try and do that yourself, I will be happy to provide guidance.

I'll close this. Let's continue discussion in #319.
