### ISSUE TITLE
New file type: Olympus "MMOR\0\0"

### ISSUE THREAD

**Issue by ygoe** [drewnoakes/metadata-extractor-dotnet#32]
I found a file with an unsupported type and could extend the code to read it. It's one of the Olympus RAW files from here: http://www.rawsamples.ch/index.php/en/olympus (Unfortunately I don't know which anymore).

Patch MetadataExtractor/Util/FileTypeDetector.cs to add this line:

```
_root.AddPath(FileType.Orf, Encoding.UTF8.GetBytes("MMOR"), new byte[] { 0x00, 0x00 });
```

**Comment by drewnoakes** [comment]
Thanks for your sleuthing on this. That website seems like a great resource too! I'm downloading the 5.5GB archive of all files right now.

Did you want to put a PR together for this? If not I'm happy to make the change for you.

**Comment by dg9ngf** [comment]
You can do it if it's easier. PR involves a GitHub fork which I haven't done. I was just reading your code to learn something about the formats and ran it a few times on my files, I'm not actually using it right now.

**Comment by drewnoakes** [comment]
Thanks to @kwhopper for fixing this issue!
