### ISSUE TITLE
Why can't I get the date time tag

### ISSUE THREAD

**Issue by melinyi** [drewnoakes/metadata-extractor-dotnet#322]
![image](https://user-images.githubusercontent.com/83648656/170031856-42d64563-a4bd-42bc-83ea-929136ff24d0.png)

If I serialize exifsubifdirectory into JSON, I can see the tag

But I can't get this value from the code, including foreach and LINQ
![image](https://user-images.githubusercontent.com/83648656/170032132-17b4df5b-9975-4739-b966-fbb8d34012ea.png)
![image](https://user-images.githubusercontent.com/83648656/170032178-5ff00d0c-3c26-4b08-8a40-2c57e0ec56aa.png)

**Comment by melinyi** [comment]
254 - New Subfile Type - Full-resolution image
256 - Image Width - 5504 pixels
257 - Image Height - 3672 pixels
258 - Bits Per Sample - 12 bits/component/pixel
259 - Compression - Sony ARW Compressed
262 - Photometric Interpretation - Color Filter Array
277 - Samples Per Pixel - 1 samples/pixel
284 - Planar Configuration - Chunky (contiguous for each subsampling pixel)
282 - X Resolution - 350 dots per inch
283 - Y Resolution - 350 dots per inch
296 - Resolution Unit - Inch
33421 - CFA Repeat Pattern Dim - 2 2
33422 - CFA Pattern - [Red,Green][Green,Blue]
28672 - Unknown tag (0x7000) - 2
28673 - Unknown tag (0x7001) - 1
28688 - Unknown tag (0x7010) - 8000 10400 12900 14100
28689 - Unknown tag (0x7011) - 4000 7200 10050 12075
28704 - Unknown tag (0x7020) - 0
273 - Strip Offsets - 730112
278 - Rows Per Strip - 3672 rows/strip
279 - Strip Byte Counts - 20210688 bytes

**Comment by melinyi** [comment]
{
  "Name": "Exif SubIFD",
  "Parent": {
    "Name": "Exif IFD0",
    "Parent": null,
    "IsEmpty": false,
    "Tags": [
      {
        "Type": 254,
        "TagType": 254,
        "Description": "Reduced-resolution image",
        "HasName": true,
        "HasTagName": true,
        "Name": "New Subfile Type",
        "TagName": "New Subfile Type",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 259,
        "TagType": 259,
        "Description": "JPEG (old-style)",
        "HasName": true,
        "HasTagName": true,
        "Name": "Compression",
        "TagName": "Compression",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 270,
        "TagType": 270,
        "Description": "                               ",
        "HasName": true,
        "HasTagName": true,
        "Name": "Image Description",
        "TagName": "Image Description",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 271,
        "TagType": 271,
        "Description": "SONY",
        "HasName": true,
        "HasTagName": true,
        "Name": "Make",
        "TagName": "Make",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 272,
        "TagType": 272,
        "Description": "DSC-RX100",
        "HasName": true,
        "HasTagName": true,
        "Name": "Model",
        "TagName": "Model",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 274,
        "TagType": 274,
        "Description": "Top, left side (Horizontal / normal)",
        "HasName": true,
        "HasTagName": true,
        "Name": "Orientation",
        "TagName": "Orientation",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 282,
        "TagType": 282,
        "Description": "350 dots per inch",
        "HasName": true,
        "HasTagName": true,
        "Name": "X Resolution",
        "TagName": "X Resolution",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 283,
        "TagType": 283,
        "Description": "350 dots per inch",
        "HasName": true,
        "HasTagName": true,
        "Name": "Y Resolution",
        "TagName": "Y Resolution",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 296,
        "TagType": 296,
        "Description": "Inch",
        "HasName": true,
        "HasTagName": true,
        "Name": "Resolution Unit",
        "TagName": "Resolution Unit",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 305,
        "TagType": 305,
        "Description": "DSC-RX100 v1.00",
        "HasName": true,
        "HasTagName": true,
        "Name": "Software",
        "TagName": "Software",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 306,
        "TagType": 306,
        "Description": "2014:08:29 15:15:36",
        "HasName": true,
        "HasTagName": true,
        "Name": "Date/Time",
        "TagName": "Date/Time",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 513,
        "TagType": 513,
        "Description": "103586",
        "HasName": false,
        "HasTagName": false,
        "Name": "Unknown tag (0x0201)",
        "TagName": "Unknown tag (0x0201)",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 514,
        "TagType": 514,
        "Description": "626479",
        "HasName": false,
        "HasTagName": false,
        "Name": "Unknown tag (0x0202)",
        "TagName": "Unknown tag (0x0202)",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 531,
        "TagType": 531,
        "Description": "Datum point",
        "HasName": true,
        "HasTagName": true,
        "Name": "YCbCr Positioning",
        "TagName": "YCbCr Positioning",
        "DirectoryName": "Exif IFD0"
      },
      {
        "Type": 50740,
        "TagType": 50740,
        "Description": "26 143 0 0",
        "HasName": false,
        "HasTagName": false,
        "Name": "Unknown tag (0xc634)",
        "TagName": "Unknown tag (0xc634)",
        "DirectoryName": "Exif IFD0"
      }
    ],
    "TagCount": 15,
    "HasError": false,
    "Errors": [
    ]
  },
  "IsEmpty": false,
  "Tags": [
    {
      "Type": 254,
      "TagType": 254,
      "Description": "Full-resolution image",
      "HasName": true,
      "HasTagName": true,
      "Name": "New Subfile Type",
      "TagName": "New Subfile Type",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 256,
      "TagType": 256,
      "Description": "5504 pixels",
      "HasName": true,
      "HasTagName": true,
      "Name": "Image Width",
      "TagName": "Image Width",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 257,
      "TagType": 257,
      "Description": "3672 pixels",
      "HasName": true,
      "HasTagName": true,
      "Name": "Image Height",
      "TagName": "Image Height",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 258,
      "TagType": 258,
      "Description": "12 bits/component/pixel",
      "HasName": true,
      "HasTagName": true,
      "Name": "Bits Per Sample",
      "TagName": "Bits Per Sample",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 259,
      "TagType": 259,
      "Description": "Sony ARW Compressed",
      "HasName": true,
      "HasTagName": true,
      "Name": "Compression",
      "TagName": "Compression",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 262,
      "TagType": 262,
      "Description": "Color Filter Array",
      "HasName": true,
      "HasTagName": true,
      "Name": "Photometric Interpretation",
      "TagName": "Photometric Interpretation",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 277,
      "TagType": 277,
      "Description": "1 samples/pixel",
      "HasName": true,
      "HasTagName": true,
      "Name": "Samples Per Pixel",
      "TagName": "Samples Per Pixel",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 284,
      "TagType": 284,
      "Description": "Chunky (contiguous for each subsampling pixel)",
      "HasName": true,
      "HasTagName": true,
      "Name": "Planar Configuration",
      "TagName": "Planar Configuration",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 282,
      "TagType": 282,
      "Description": "350 dots per inch",
      "HasName": true,
      "HasTagName": true,
      "Name": "X Resolution",
      "TagName": "X Resolution",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 283,
      "TagType": 283,
      "Description": "350 dots per inch",
      "HasName": true,
      "HasTagName": true,
      "Name": "Y Resolution",
      "TagName": "Y Resolution",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 296,
      "TagType": 296,
      "Description": "Inch",
      "HasName": true,
      "HasTagName": true,
      "Name": "Resolution Unit",
      "TagName": "Resolution Unit",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 33421,
      "TagType": 33421,
      "Description": "2 2",
      "HasName": true,
      "HasTagName": true,
      "Name": "CFA Repeat Pattern Dim",
      "TagName": "CFA Repeat Pattern Dim",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 33422,
      "TagType": 33422,
      "Description": "[Red,Green][Green,Blue]",
      "HasName": true,
      "HasTagName": true,
      "Name": "CFA Pattern",
      "TagName": "CFA Pattern",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 28672,
      "TagType": 28672,
      "Description": "2",
      "HasName": false,
      "HasTagName": false,
      "Name": "Unknown tag (0x7000)",
      "TagName": "Unknown tag (0x7000)",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 28673,
      "TagType": 28673,
      "Description": "1",
      "HasName": false,
      "HasTagName": false,
      "Name": "Unknown tag (0x7001)",
      "TagName": "Unknown tag (0x7001)",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 28688,
      "TagType": 28688,
      "Description": "8000 10400 12900 14100",
      "HasName": false,
      "HasTagName": false,
      "Name": "Unknown tag (0x7010)",
      "TagName": "Unknown tag (0x7010)",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 28689,
      "TagType": 28689,
      "Description": "4000 7200 10050 12075",
      "HasName": false,
      "HasTagName": false,
      "Name": "Unknown tag (0x7011)",
      "TagName": "Unknown tag (0x7011)",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 28704,
      "TagType": 28704,
      "Description": "0",
      "HasName": false,
      "HasTagName": false,
      "Name": "Unknown tag (0x7020)",
      "TagName": "Unknown tag (0x7020)",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 273,
      "TagType": 273,
      "Description": "730112",
      "HasName": true,
      "HasTagName": true,
      "Name": "Strip Offsets",
      "TagName": "Strip Offsets",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 278,
      "TagType": 278,
      "Description": "3672 rows/strip",
      "HasName": true,
      "HasTagName": true,
      "Name": "Rows Per Strip",
      "TagName": "Rows Per Strip",
      "DirectoryName": "Exif SubIFD"
    },
    {
      "Type": 279,
      "TagType": 279,
      "Description": "20210688 bytes",
      "HasName": true,
      "HasTagName": true,
      "Name": "Strip Byte Counts",
      "TagName": "Strip Byte Counts",
      "DirectoryName": "Exif SubIFD"
    }
  ],
  "TagCount": 21,
  "HasError": false,
  "Errors": [
  ]
}

**Comment by melinyi** [comment]
Sorry, I ignored parent Tags

**Comment by drewnoakes** [comment]
Can you show more of your code?
