### ISSUE TITLE
Does it works with unity game engine?

### ISSUE THREAD

**Issue by UsmanKhanLodhi** [drewnoakes/metadata-extractor-dotnet#346]
Hello,

I'm currently working on integrating it with my Unity project. However, I've encountered some issues. It seems that the metadata extractor is not being found. Interestingly, when I integrate it into a .NET console project, it works perfectly. Could you please provide some guidance on the settings so that I can successfully use it with the Unity game engine?

Thank you!

**Comment by drewnoakes** [comment]
I'm not familiar enough with Unity to say, but I can't see any reason it wouldn't work. What error do you see?

**Comment by songjihu** [comment]
I've tried it in Unity, and it works. You just need to place the compiled DLL into the 'Assets' directory. I'm using VS2022 and Unity 2021.3.10f1.
我在unity里试过了，可以的，把编译出来的dll放进asset目录就可以了。我用的是vs2022 和 unity2021.3.10f1

**Comment by drewnoakes** [comment]
Thanks for confirming and providing steps to get it working. Closing this for now.

**Comment by UsmanKhanLodhi** [comment]
Hello , 
Is their any solution ?
The error is :

"Assembly 'Assets/MetadataExtractor.dll' will not be loaded due to errors:
Unable to resolve reference 'XmpCore'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector."

**Comment by songjihu** [comment]
> Hello , Is their any solution ? The error is :
> 
> "Assembly 'Assets/MetadataExtractor.dll' will not be loaded due to errors: Unable to resolve reference 'XmpCore'. Is the assembly missing or incompatible with the current platform? Reference validation can be disabled in the Plugin Inspector."
Put XmpCore.dll file into Assets folder too

**Comment by UsmanKhanLodhi** [comment]
> > Hello , Is their any solution ? The error is :
> > "Assembly 'Assets/MetadataExtractor.dll' will not be loaded due to errors: Unable to resolve reference 'XmpCore'. Is the assembly missing or incompatible with the current platform? Reference validation can be disabled in the Plugin Inspector."
> > Put XmpCore.dll file into Assets folder too


Could you share a test project with me ?

**Comment by songjihu** [comment]
> > > Hello , Is their any solution ? The error is :
> > > "Assembly 'Assets/MetadataExtractor.dll' will not be loaded due to errors: Unable to resolve reference 'XmpCore'. Is the assembly missing or incompatible with the current platform? Reference validation can be disabled in the Plugin Inspector."
> > > Put XmpCore.dll file into Assets folder too
> 
> Could you share a test project with me ?

I can share my dll files. These files worked in my project.
[Metadata.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/13277292/Metadata.zip)
