### ISSUE TITLE
Reported JPEG Thumbnail Offsets are incorrect

### ISSUE THREAD

**Issue by kwhopper** [drewnoakes/metadata-extractor-dotnet#35]
JPEG byte offsets for embedded thumbnails are not correct. The offset is calculated relative to the segment, and does not include the offset of the segment relative to the file start. Usually, it's off by the SOI + TIFF markers or 6 + 6 = 12. This would not be true for App1 fragments in the test data since they won't contain SOI, and makes this more complicated than it seems.

**Comment by kwhopper** [comment]
I commented more in the referenced pull request. The fix in the PR may or may not be desirable.

**Comment by twest820** [comment]
Drew, would it be possible to get @kwhopper's pull request into the next release?

In the meantime, I'm thinking to work around this using an approach similar to that illustrated in the spike code below.

            ExifThumbnailDirectory thumbnails = ...
            Assert.IsTrue(thumbnails.GetDescription(ExifThumbnailDirectory.TagCompression).StartsWith("JPEG"));
            long thumbnailOffset = Int64.Parse(thumbnails.GetDescription(ExifThumbnailDirectory.TagThumbnailOffset).Split(' ')[0]);
            const int maxIssue35Offset = 12;
            int thumbnailLength = Int32.Parse(thumbnails.GetDescription(ExifThumbnailDirectory.TagThumbnailLength).Split(' ')[0]) + maxIssue35Offset;
            byte[] thumbnail = new byte[thumbnailLength];
            using (FileStream imageStream = new FileStream(imagePath, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                imageStream.Seek(thumbnailOffset, SeekOrigin.Begin);
                imageStream.Read(thumbnail, 0, thumbnailLength);
            }

            // work around Metadata Extractor issue #35
            Assert.IsTrue(thumbnailLength > maxIssue35Offset + 1);
            int issue35Offset = 0;
            for (int offset = 0; offset <= maxIssue35Offset; ++offset)
            {
                // 0xffd8 is the JFIF start of image segment indicator
                if ((thumbnail[offset] == 0xff) && (thumbnail[offset + 1] == 0xd8))
                {
                    issue35Offset = offset;
                    break;
                }
            }

            using (MemoryStream thumbnailStream = new MemoryStream(thumbnail, issue35Offset, thumbnailLength - issue35Offset, false))
            {
                JpegBitmapDecoder jpegDecoder = new JpegBitmapDecoder(thumbnailStream, BitmapCreateOptions.None, BitmapCacheOption.None);
                WriteableBitmap writeableBitmap = new WriteableBitmap(jpegDecoder.Frames[0]);
            }
