### ISSUE TITLE
Bump net4.5 -> net462

### ISSUE THREAD

**Issue by iamcarbon** [drewnoakes/metadata-extractor-dotnet#362]
What are our thoughts on bumping the minimum net framework version from net452 (out of support) to net462?

This would allow us to utilize FrozenDictionary and FrozenSet from the https://www.nuget.org/packages/System.Collections.Immutable package, which have some nice performance improvements.

.NET 4.5.2 is out of support, while .NET 4.6.2 should be supported until at least 2026.

**Comment by drewnoakes** [comment]
I was on the fence about removing 3.5 :)

But bumping 4.x would be nice, I agree.

Shout out to all users: what framework version are your apps targeting?

**Comment by drewnoakes** [comment]
Fixed in https://github.com/drewnoakes/metadata-extractor-dotnet/pull/382
