### ISSUE TITLE
Date formats?

### ISSUE THREAD

**Issue by dyardyGIT** [drewnoakes/metadata-extractor-dotnet#41]
Using GpsDirectory.TagDateStamp i get date formats like 
"GPS - GPS Date Stamp - 2016-03-14"
and also 
"GPS - GPS Date Stamp - 2016:03:18"

why am i seeing different formats?

**Comment by drewnoakes** [comment]
The latest code (on master, not yet published) provides consistent output. I'll get a build up on NuGet shortly.

**Comment by drewnoakes** [comment]
Take a look at v1.2.0. Please re-open this if you still see this behaviour.
