### ISSUE TITLE
incompability of SharpZipLib dependency with Windows 8.1 apps

### ISSUE THREAD

**Issue by michaelosthege** [drewnoakes/metadata-extractor-dotnet#50]
The compiler threw an error:
`Cannot find type System.ApplicationException in module mscorlib.dll.`
By installing the dependencies one-by-one, I found that this was due to SharpZipLib.
A workaround is to use the ICSharpCode.SharpZipLib.Portable package instead. (And ignoring dependencies in the NuGet package manager.)

Taking issue #48 into account, it might be time to get rid of the whole SharpZipLib dependency.

**Comment by drewnoakes** [comment]
Please take a look at `2.0.0-rc1` on NuGet and see if it meets your requirements.
