### ISSUE TITLE
Regression tests should not use machine's locale

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#89]
Developers currently cannot run the regression tests in locales that format things differently to `en-GB` (and some other English-language locales). This was identified by @Nadahar in drewnoakes/metadata-extractor#233.

The regression test program must use invariant culture on its thread:

    System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;

This should be compared with the [equivalent issue](https://github.com/drewnoakes/metadata-extractor/issues/236) in the Java project.

**Comment by patricksadowski** [comment]
I ran into the same issue. May I fix it?

**Comment by kwhopper** [comment]
A PR for review is always welcome. Thanks
