### ISSUE TITLE
Library not working in WebJob for Microsoft Azure Blob-Storage

### ISSUE THREAD

**Issue by mikey74L** [drewnoakes/metadata-extractor-dotnet#94]
My WebSite has an Azure Web Job for watching on new blobs added to the container. Following function would be called:

`public static void NewUploadPicture([QueueTrigger("upload-picture")] NewUploadPictureModel newMessage,
                                            [Blob("upload-picture/{BlobName}", FileAccess.Read)] Stream uploadPicture)`

When I use the "uploadPicture" stream to extract the exif data from the uploaded jpeg with following statement:

`IEnumerable<MetadataExtractor.Directory> directories = ImageMetadataReader.ReadMetadata(uploadPicture);`

the Library throws an exception that the file format is not supported.

But when I download the azure blob to my local disk and then use the library on the saved file it works and the metadata could be readed.

Is there any workaround for this problem, or is it just a bug?

**Comment by drewnoakes** [comment]
Do you have a stack trace?

**Comment by drewnoakes** [comment]
Also, what is the output of `FileTypeDetector.DetectFileType(stream)` when you pass your Azure stream?

**Comment by mikey74L** [comment]
I think I have found the problem.

I'm using the stream that is provided by the Web Jobs SDK several times. So before I try to read the EXIF-Data with metadata extractor I'm executing following code:

`            Bitmap bmp = new Bitmap(pictureStream);`

And I forgot to set the position of the stream to 0 before I use the stream again with the metadata extractor.

Now it works all as expected.

Sorry the bug was in my code not in the library.

**Comment by drewnoakes** [comment]
Thanks for following up. Glad it's working.
